config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
  end

  resources :users, :routes, :favorites, :stop_requests, :drivers
  root to: 'visitors#index'
end

app/models/stop_request.rb
class StopRequest < ActiveRecord::Base
  enum status: [:requested, :taken, :ignored]
  belongs_to :client
  belongs_to :driver

  validates :client_id, presence: true
  validates :driver_id, presence: true
end

app/controllers/stop_requests_controller.rb
class StopRequestsController < ApplicationController
  before_action :set_stop_request, only: [:show, :edit, :update, :destroy]

  # GET /stop_requests
  # GET /stop_requests.json
  def index
    @stop_requests = StopRequest.all
  end

  # GET /stop_requests/1
  # GET /stop_requests/1.json
  def show
  end

  # GET /stop_requests/new
  def new
    @stop_request = StopRequest.new
  end

  # GET /stop_requests/1/edit
  def edit
  end

  # POST /stop_requests
  # POST /stop_requests.json
  def create
    @stop_request = StopRequest.new(stop_request_params)

    respond_to do |format|
      if @stop_request.save
        format.html { redirect_to @stop_request, notice: 'Stop request was successfully created.' }
        format.json { render :show, status: :created, location: @stop_request }
      else
        format.html { render :new }
        format.json { render json: @stop_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stop_requests/1
  # PATCH/PUT /stop_requests/1.json
  def update
    respond_to do |format|
      if @stop_request.update(stop_request_params)
        format.html { redirect_to @stop_request, notice: 'Stop request was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop_request }
      else
        format.html { render :edit }
        format.json { render json: @stop_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stop_requests/1
  # DELETE /stop_requests/1.json
  def destroy
    @stop_request.destroy
    respond_to do |format|
      format.html { redirect_to stop_requests_url, notice: 'Stop request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop_request
      @stop_request = StopRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_request_params
      params[:stop_request]
    end
end

app/helpers/stop_requests_helper.rb
module StopRequestsHelper
end

app/views/stop_requests/_form.html.erb
<%= form_for(@stop_request) do |f| %>
  <% if @stop_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop_request.errors.count, "error") %> prohibited this stop_request from being saved:</h2>

      <ul>
      <% @stop_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stop_requests/edit.html.erb
<h1>Editing Stop Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop_request %> |
<%= link_to 'Back', stop_requests_path %>

app/views/stop_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stop Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stop_requests.each do |stop_request| %>
      <tr>
        <td><%= link_to 'Show', stop_request %></td>
        <td><%= link_to 'Edit', edit_stop_request_path(stop_request) %></td>
        <td><%= link_to 'Destroy', stop_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop request', new_stop_request_path %>

app/views/stop_requests/new.html.erb
<h1>New Stop Request</h1>

<%= render 'form' %>

<%= link_to 'Back', stop_requests_path %>

app/views/stop_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stop_request_path(@stop_request) %> |
<%= link_to 'Back', stop_requests_path %>